[project]
name = "graphyard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.0.0",
    "catboost>=1.2.8",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.11",
    "skforecast>=0.19.1",
    "vl-convert-python>=1.9.0",
    "weasyprint>=67.0",
    "xgboost>=3.1.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
